#\u7AEF\u53E3\u914D\u7F6E
server:
  port: 1989
#\u65E5\u5FD7\u914D\u7F6E
logging:
  level:
   houzm.accumulation.limit: debug #\u683C\u5F0F\u4E3Alogging.level.\u5305\u540D = \u7EA7\u522B\uFF0C\u5982\u679C\u4E0D\u914D\u7F6E\u5305\u540D\u62A5\u9519\uFF1Aorg.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'logging.level' to java.util.Map<java.lang.String, java.lang.String>
#\u5173\u95ED\u6D4F\u89C8\u5668\u6807\u7B7E\u9875\u7684icon
spring:
  mvc:
    favicon:
      enabled: false